const PRIMARY = '#F95759';
const PRIMARY_LIGHT = '#FFA8A9';
const PRIMARY_DARK = '#D03F40';
const SECONDARY = '#E3632D';
const SECONDARY_LIGHT = '#F7A380';
const SECONDARY_DARK = '#CE3D00';
const TERIARY = '#2D8ABE';
const TERIARY_LIGHT = '#9ACDEA';
const TERIARY_DARK = '#056296';

const WHITE = '#FFF';
const LIGHT_GRAY = '#F2F3F4';
const MID_GRAY = '#DADEDF';
const GRAY = '#C1C7C9';
const DARK_GRAY = '#A7B0B2';
const BLACK = '#000';

export default {
  PRIMARY,
  PRIMARY_LIGHT,
  PRIMARY_DARK,
  SECONDARY,
  SECONDARY_LIGHT,
  SECONDARY_DARK,
  TERIARY,
  TERIARY_LIGHT,
  TERIARY_DARK,
  WHITE,
  LIGHT_GRAY,
  MID_GRAY,
  GRAY,
  DARK_GRAY,
  BLACK
};
